quarkus:
  datasource:
    db-kind: mysql
    username: admin
    password: admin
    jdbc:
      url: jdbc:mysql://localhost:3306/movie_svc
  liquibase:
    change-log: liquibase/changes.xml
    migrate-at-start: true
  micrometer:
    binder:
      http-client.enabled: true
