apiVersion: v1
kind: Service
metadata:
  name: rabbit-broker
spec:
  ports:
    - name: rabbit-port
      port: 5672
      targetPort: 5672
    - name: management-rabbit-port
      port: 15672
      targetPort: 15672
    - name: management-rabbit-prometheus-port
      port: 15692
      targetPort: 15692
  selector:
    app: rabbit-broker

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-broker
  labels:
    app: rabbit-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-broker
  template:
    metadata:
      annotations:
        prometheus/scrape_enabled: "true"
        prometheus/scrape_endpoint: "/metrics"
        prometheus/scrape_port: "15692"
      labels:
        app: rabbit-broker
    spec:
      containers:
        - name: rabbit
          image: "rabbitmq:3.8.8-management"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 128Mi


